apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployhub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jeneeldumasia/DeployHubK8s.git
    targetRevision: HEAD
    path: k8s_deploy/overlays/k3s
  destination:
    server: https://kubernetes.default.svc
    namespace: deployhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
