apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: deployhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-private-key
      containers:
        - name: frontend
          image: 654654525548.dkr.ecr.us-east-1.amazonaws.com/deployhub-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: deployhub
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 3080
  type: NodePort
